apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pg9ovqqo2-python
  janus-idp.io/tekton: pg9ovqqo2-python
  backstage.io/kubernetes-id: pg9ovqqo2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pg9ovqqo2-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
